spring:
  datasource:
    url: jdbc:postgresql://db:5432/car-rest-service
    username: postgres
    password: baloo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-e4pibinhg6lsobn4.us.auth0.com/
auth0:
  audience: https://car-service
springdoc:
  api-docs:
    path: /api-docs
